name: ReneNicholson
favicon: null
layout_spectrum: 0.749676879029721
typography_spectrum: 0.6486943576019257
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.9362207239028066
  lightness: 0.19372330652549863
  saturation: 0.8547749442514032
  rhythmicContrast: 0.4995215714443475
purpose: []
